# Generated by Django 4.2.5 on 2024-11-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
