# Generated by Django 4.2.7 on 2023-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='youssef@gmail.com', max_length=254),
        ),
    ]
