# Generated by Django 4.2.7 on 2023-11-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_rename_name_utilisateur_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(default='youssef@gmail.com', max_length=254, unique=True),
        ),
    ]
