# Generated by Django 4.2.5 on 2024-08-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_rename_name_utilisateur_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_name',
        ),
    ]
